name: typesense
description: Dart client library for accessing the Typesense HTTP API.
version: 0.0.1
homepage: https://typesense.org/

environment:
  sdk: ">=2.10.0-0 <3.0.0"

dependencies:
  http: ^0.12.2
  collection: ^1.14.13
  
dev_dependencies:
  test: ^1.15.7
  mockito: ^4.1.4
