name: typesense
description: Dart client library for accessing the HTTP API of Typesense search engine.
version: 0.6.0
repository: https://github.com/typesense/typesense-dart

environment:
  sdk: ^3.6.1

dependencies:
  http: ^1.3.0
  crypto: ^3.0.6

dev_dependencies:
  test: ^1.25.14
  mockito: ^5.4.5
  lints: ^6.0.0
  build_runner: ^2.4.14
  analyzer: ^10.0.0
