name: console_simple
description: A simple command-line application to showcase typesense examples.
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  typesense:
    path: ../../
  logging: ^1.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
